kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: 5min-idp
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP
